<?
/**
 * @var \Customer\AddressBook\Block\AddedBook $block
 */

?>
<form action="<?= $block->getFormAction() ?>" method="post">

    <label for="">First name</label>
    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" >
    <input name="first_name" type="text">
    <label for="">Last name</label>
    <input name="last_name" type="text">
    <label for="">Phone</label>
    <input name="phone_number" type="text">
    <input type="hidden" value="<?= $block->getIdCustomer()?>" name="customer_id">
    <input type="submit" value="Save address book">
</form>